project:
  type: website
  output-dir: docs

website:
  title: "M10 Assignment"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Dashboard
      - href: Essay on Shiny Apps.qmd
        text: Essay on Shiny Apps
      - href: Essay on Shiny Live.qmd
        text: Essay on Shiny Live
    tools:
      - icon: github
        href: https://github.com

format:
  html:
    backgroundcolor: black
    fontcolor: "lightgreen"
    linkcolor: "lightblue"
    theme: cosmo
    css: styles.css
    toc: false
    

editor: visual

